### ISSUE TITLE
Add TweetyNET pipeline to PyHa

### ISSUE THREAD

**Issue by JacobGlennAyers** [UCSD-E4E/PyHa#102]
In a similar manner to the way Microfaune is set up, add a folder that has all of the independent TweetyNET functions and relevant pre-trained models, that are then called by IsoAutio.py to use in the generate_automated_labels_tweetynet function.

**Comment by sprestrelski** [comment]
Implemented in the [TweetyNET Integrations 2 branch](https://github.com/UCSD-E4E/PyHa/tree/TweetyNet_integrations_2_main).
