### ISSUE TITLE
Implement binaries stripping for jupyter notebook to rescript size

### ISSUE THREAD

**Issue by Sean1572** [UCSD-E4E/PyHa#142]

**Comment by JacobGlennAyers** [comment]
Wouldn't that just ignore the history that is causing the repo to be large in the first place?

**Comment by Sean1572** [comment]
This must have been written during a collab meeting, and I've forgotten the context. I think you are right the issue is the history, but we should probably have better guidelines for handling notebook files

Probably safe to close this issue.
