### ISSUE TITLE
Increase efficiency of IoU scores with Linear Algebra

### ISSUE THREAD

**Issue by JacobGlennAyers** [UCSD-E4E/PyHa#15]
The current approach to finding the IoU scores is an O(n^2) nested for-loop approach. It can be refactored taking advantage of numpy's linear algebra capabilities to be closer to O(n). Low priority for now since we merely need to demo, but will be crucial as we get closer to larger-scale tests.

**Comment by JacobGlennAyers** [comment]
Relabeled as medium priority due to the slow run-time when trying to garner statistics in the optimization process. It can take up to ten minutes to run the algorithm 100 times on six clips.

**Comment by JacobGlennAyers** [comment]
We would first want to add a bunch of timing statements in the global_IoU_Statistics() function to identify where the largest timing bottlenecks exist. I am pretty certain the generation of the IoU Matrices are the largest bottleneck. Linear algebra might be able to speed it up, though a simpler approach could be simply using the "OFFSET" and "DURATION" column times directly instead of creating numpy arrays for the task.

**Comment by JacobGlennAyers** [comment]
clip_IoU is currently the largest bottleneck

**Comment by sprestrelski** [comment]
Throwing out annotations that a union of 0 makes the Screaming Piha data much faster, while giving equivalent statistics. This makes it actually feasible to run on large datasets 😃 

| Dataset | Method | skip | lin-alg | lin-alg + skip |
|--|--|--|--|--|
| Screaming Piha | clip_IoU | 286.4s | 171.8s | 23.4s |
| Screaming Piha | automated_labeling_statistics() | 49.9s | 31.1s | 5.6s |
| 25% Mixed Bird | automated_labeling_statistics() | - | 2221.1s | 337.7s |

Notebook and relevant files (e.g. modified statistics.py file) were moved to the [passive-acoustic-biodiversity repo](https://github.com/UCSD-E4E/passive-acoustic-biodiversity/tree/master/IoU_Performance).   


**Description of algorithms used:**  
skip: modified original version, skipping calculations when end<min, start>max
lin: matrix transposition for intersection, nested for loop
lin-skip: matrix transposition for intersection, nested for loop and skipping calculations when intersection = 0 (highest bound = $O(n^2)$

**Benchmarks for Screaming Piha dataset (clip_IoU):**  
![image](https://user-images.githubusercontent.com/33042752/178612950-72bc6481-abe6-4a03-aafd-a2320ac89c27.png)  
**Benchmarks for Screaming Piha dataset (automated_labeling_statistics):**  
![image](https://user-images.githubusercontent.com/33042752/178613176-5885befa-bde3-44df-b077-fc203744556d.png)

**Benchmarks for 25% Mixed Bird (automated_labeling_statistics):**  
![image](https://user-images.githubusercontent.com/33042752/178622202-0d28ecac-73c2-44e0-8872-a812322e0917.png)
