### ISSUE TITLE
Create a function that connects annotations of the same class that overlap/touch to one-another

### ISSUE THREAD

**Issue by JacobGlennAyers** [UCSD-E4E/PyHa#47]
In a Kaleidoscope-inspired dataframe, if the offset + duration overlaps with the next annotations offset, connect them together.

**Comment by himanshu007-creator** [comment]
Hi, i am really interested to work on this issue, but can you break this to me in easy terms?

**Comment by JacobGlennAyers** [comment]
Hi there himanshu! If you look at the pandas dataframe in the IsoAutio_Tutorial for the automated_df or the human_df, you will see two columns called "OFFSET" and "DURATION". These represent the start and end times of an audio annotation with respect to the larger clip. The idea behind the function I describe is that if an annotation is of the same class as another and the "OFFSET" + "DURATION" time overlaps ,I,E, the end time is greater than or equal to the "OFFSET" of another annotation in the same class (class is determined by the "MANUAL ID" column. Then you combine the two annotations together, as in the start of the first annotation with respect to time, becomes the start of the new annotation, and the end of the later annotation, becomes the end of the new annotation.

**Comment by JacobGlennAyers** [comment]
More or less completed with the "Label Chunker" function in the annotation_post_processing.py file in the PyHa folder. Will re-open if we need to do this in a more dynamic manner.
